# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 14:52
from __future__ import unicode_literals

import ckeditor.fields
import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extended_flatpages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MyFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('source', models.CharField(max_length=20)),
                ('domain', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NigeriaState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_code', models.CharField(max_length=200)),
                ('poll_title', models.CharField(default='Leave Empty', help_text='Short description that identify the question', max_length=200)),
                ('poll_question', ckeditor.fields.RichTextField()),
                ('poll_domain', models.CharField(choices=[('ECONOMY', 'Economy'), ('POLITICS', 'Politics'), ('SOCIAL', 'Social')], max_length=20)),
                ('poll_date', models.DateField()),
                ('poll_state', models.CharField(choices=[('PUBLISH', 'PUBLISH'), ('UNPUBLISH', 'UNPUBLISH')], default='UNPUBLISH', max_length=20)),
                ('poll_author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polloption_text', models.TextField()),
                ('polloption_questioncode', models.CharField(default='', max_length=50)),
                ('polloption_code', models.CharField(default='', max_length=200)),
                ('polloption_score', models.IntegerField(default=0)),
                ('polloption_questiontitle', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=30)),
                ('lastname', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('local_government', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.LG')),
                ('state_of_origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.NigeriaState')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('domain', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapyFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('link', models.CharField(blank=True, max_length=30)),
                ('image', models.CharField(blank=True, max_length=30)),
                ('publish_on', models.CharField(blank=True, max_length=30)),
                ('scrap_on', models.CharField(blank=True, max_length=30)),
                ('story', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoryFlatPage',
            fields=[
                ('cmsflatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='extended_flatpages.CMSFlatPage')),
                ('story_is_hero', models.BooleanField(default=False)),
                ('story_hero_image', models.FileField(blank=True, upload_to='passport/%Y/%m/%d')),
                ('story_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content')),
                ('story_domain', models.CharField(choices=[('ECONOMY', 'Economy'), ('POLITICS', 'Politics'), ('SOCIAL', 'Social')], max_length=20)),
                ('story_status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('UNPUBLISH', 'UNPUBLISH'), ('PUBLISH', 'PUBLISH'), ('COMPLETE', 'COMPLETE'), ('END-OF-LIFE', 'END-OF-LIFE')], default='DRAFT', max_length=20)),
                ('story_date', models.DateField(default=datetime.datetime(2017, 8, 6, 15, 52, 58, 439481))),
                ('story_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('extended_flatpages.cmsflatpage',),
        ),
        migrations.CreateModel(
            name='SurveyTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveytag_title', models.CharField(default='', max_length=100)),
                ('surveytag_description', ckeditor.fields.RichTextField()),
                ('surveytag_tag', models.CharField(default='', max_length=100)),
                ('surveytag_date', models.DateField()),
                ('surveytag_domain', models.CharField(choices=[('ECONOMY', 'Economy'), ('POLITICS', 'Politics'), ('SOCIAL', 'Social')], max_length=20)),
                ('surveytag_status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('UNPUBLISH', 'UNPUBLISH'), ('PUBLISH', 'PUBLISH'), ('COMPLETE', 'COMPLETE'), ('END-OF-LIFE', 'END-OF-LIFE')], default='DRAFT', max_length=20)),
                ('survey_image', models.FileField(blank=True, upload_to='passport/%Y/%m/%d')),
                ('surveytag_owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPollOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('date', models.DateField(auto_now=True)),
                ('optionquestion', models.TextField(default='')),
                ('optiontitle', models.TextField(default='')),
                ('option', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='app.PollOption')),
                ('user', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_surveytag',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='app.SurveyTag'),
        ),
        migrations.AddField(
            model_name='lg',
            name='state',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.NigeriaState'),
        ),
    ]
