# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_code', models.CharField(max_length=20)),
                ('poll_question', models.TextField()),
                ('poll_domain', models.CharField(choices=[('ECONOMY', 'Economy'), ('POLITICS', 'Politics'), ('SOCIAL', 'Social')], max_length=20)),
                ('poll_date', models.DateField()),
            ],
        ),
    ]
