# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 10:14
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_code', models.CharField(max_length=20)),
                ('poll_title', models.CharField(default='', help_text='Short description that identify the question', max_length=50)),
                ('poll_question', ckeditor.fields.RichTextField()),
                ('poll_domain', models.CharField(choices=[('ECONOMY', 'Economy'), ('POLITICS', 'Politics'), ('SOCIAL', 'Social')], max_length=20)),
                ('poll_date', models.DateField()),
                ('poll_state', models.CharField(choices=[('PUBLISH', 'PUBLISH'), ('UNPUBLISH', 'UNPUBLISH')], default='UNPUBLISH', max_length=20)),
                ('poll_author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polloption_text', models.TextField()),
                ('polloption_questioncode', models.CharField(default='', max_length=50)),
                ('polloption_code', models.CharField(default='', max_length=200)),
                ('polloption_score', models.IntegerField(default=0)),
                ('polloption_questiontitle', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveytag_title', models.TextField()),
                ('surveytag_description', ckeditor.fields.RichTextField()),
                ('surveytag_tag', models.CharField(default='', max_length=100)),
                ('surveytag_date', models.DateField()),
                ('surveytag_domain', models.CharField(choices=[('ECONOMY', 'Economy'), ('POLITICS', 'Politics'), ('SOCIAL', 'Social')], max_length=20)),
                ('surveytag_status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('UNPUBLISH', 'UNPUBLISH'), ('PUBLISH', 'PUBLISH'), ('COMPLETE', 'COMPLETE'), ('END-OF-LIFE', 'END-OF-LIFE')], default='DRAFT', max_length=20)),
                ('surveytag_owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_surveytag',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='app.SurveyTag'),
        ),
    ]
