# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 14:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyflatpage',
            name='story_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 6, 15, 53, 30, 589246)),
        ),
    ]
