# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='poll_title',
            field=models.CharField(default='', help_text='Short description that identify the question', max_length=50),
        ),
    ]
