# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extended_flatpages', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryFlatPage',
            fields=[
                ('cmsflatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='extended_flatpages.CMSFlatPage')),
                ('story_is_hero', models.BooleanField(default=False)),
                ('story_hero_image', models.FileField(blank=True, upload_to='passport/%Y/%m/%d')),
                ('story_domain', models.CharField(choices=[('ECONOMY', 'Economy'), ('POLITICS', 'Politics'), ('SOCIAL', 'Social')], max_length=20)),
                ('story_status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('UNPUBLISH', 'UNPUBLISH'), ('PUBLISH', 'PUBLISH'), ('COMPLETE', 'COMPLETE'), ('END-OF-LIFE', 'END-OF-LIFE')], default='DRAFT', max_length=20)),
            ],
            bases=('extended_flatpages.cmsflatpage',),
        ),
    ]
