# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 14:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170806_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyflatpage',
            name='story_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 6, 15, 54, 20, 117938)),
        ),
    ]
