# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 08:11
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_poll_poll_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_question',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
