# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170616_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='poll_state',
            field=models.CharField(choices=[('PUBLISH', 'PUBLISH'), ('UNPUBLISH', 'UNPUBLISH')], default='UNPUBLISH', max_length=20),
        ),
    ]
