# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 21:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_storyflatpage_story_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NigeriaState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=30)),
                ('lastname', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('local_government', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.LG')),
                ('state_of_origin', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.NigeriaState')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='storyflatpage',
            name='story_date',
            field=models.DateField(default=datetime.datetime(2017, 6, 26, 22, 28, 56, 864537)),
        ),
        migrations.AddField(
            model_name='lg',
            name='state',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.NigeriaState'),
        ),
    ]
