# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_poll_poll_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polloption_text', models.TextField()),
                ('polloption_questioncode', models.CharField(default='', max_length=50)),
                ('polloption_code', models.CharField(max_length=50)),
                ('polloption_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Poll')),
            ],
        ),
    ]
