# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 21:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170626_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='local_government',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.LG'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state_of_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.NigeriaState'),
        ),
        migrations.AlterField(
            model_name='storyflatpage',
            name='story_date',
            field=models.DateField(default=datetime.datetime(2017, 6, 26, 22, 31, 42, 390799)),
        ),
    ]
