# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 10:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170626_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyflatpage',
            name='story_date',
            field=models.DateField(default=datetime.datetime(2017, 6, 28, 11, 37, 43, 364585)),
        ),
        migrations.AlterField(
            model_name='surveytag',
            name='surveytag_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
