# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_polloption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polloption',
            name='polloption_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.RemoveField(
            model_name='polloption',
            name='polloption_question',
        ),
        migrations.AddField(
            model_name='polloption',
            name='polloption_question',
            field=models.ManyToManyField(to='app.Poll'),
        ),
    ]
