# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 11:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170628_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='poll_code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_title',
            field=models.CharField(default='Leave Empty', help_text='Short description that identify the question', max_length=200),
        ),
        migrations.AlterField(
            model_name='storyflatpage',
            name='story_date',
            field=models.DateField(default=datetime.datetime(2017, 6, 28, 12, 50, 8, 35004)),
        ),
    ]
