# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 19:37
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20170628_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPollOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.CharField(blank=True, default='', max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('optiontext', models.TextField(default='')),
                ('option', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='app.PollOption')),
                ('user', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='storyflatpage',
            name='story_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 1, 20, 37, 42, 205947)),
        ),
    ]
