# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170616_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polloption',
            name='polloption_question',
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_options',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.PollOption'),
        ),
    ]
