# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170616_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='poll_options',
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_options',
            field=models.ManyToManyField(default='', to='app.PollOption'),
        ),
    ]
