# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 20:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170701_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpolloption',
            old_name='optiontext',
            new_name='optionquestion',
        ),
        migrations.AddField(
            model_name='userpolloption',
            name='optiontitle',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='storyflatpage',
            name='story_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 1, 21, 10, 31, 547353)),
        ),
    ]
