# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170616_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='poll_options',
        ),
        migrations.AddField(
            model_name='polloption',
            name='polloption_score',
            field=models.IntegerField(default=0),
        ),
    ]
