# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 23:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170702_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='domain',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='storyflatpage',
            name='story_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 2, 0, 20, 55, 300303)),
        ),
    ]
