# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170617_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='polloption',
            name='polloption_questiontitle',
            field=models.CharField(default='', max_length=50),
        ),
    ]
