# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 07:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170702_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyflatpage',
            name='story_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 2, 8, 7, 26, 915155)),
        ),
        migrations.AlterField(
            model_name='userpolloption',
            name='ipaddress',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
