# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 23:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_polloption_polloption_questiontitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='poll_author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
