# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 12:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170703_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('source', models.CharField(max_length=20)),
                ('domain', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='storyflatpage',
            name='story_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 3, 13, 21, 52, 129483)),
        ),
    ]
