# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 07:37
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0015_auto_20170703_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyflatpage',
            name='story_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storyflatpage',
            name='story_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 8, 8, 37, 9, 478293)),
        ),
    ]
