# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 08:24
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20170708_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyflatpage',
            name='story_feature_image',
        ),
        migrations.AddField(
            model_name='storyflatpage',
            name='story_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='storyflatpage',
            name='story_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 8, 9, 24, 24, 144125)),
        ),
    ]
