# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 05:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20170708_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, help_text='Where You Presently Reside', max_length=30),
        ),
        migrations.AlterField(
            model_name='storyflatpage',
            name='story_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 11, 6, 57, 37, 683427)),
        ),
    ]
