# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 15:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20170712_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapyFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('title', models.TextField()),
                ('link', models.TextField()),
                ('image', models.TextField()),
                ('publish_on', models.TextField()),
                ('scrap_on', models.CharField(blank=True, max_length=30)),
                ('story', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='storyflatpage',
            name='story_date',
            field=models.DateField(default=datetime.datetime(2017, 7, 27, 16, 31, 43, 556809)),
        ),
    ]
